### PR TITLE
Book mgr

### PR DESCRIPTION
**Pull request by JBenda**
BEGINRELEASENOTES

- update Marlin Scheme to svg
- update MarlinBook Scheme
- add examples for MarlinBook 

ENDRELEASENOTES

### CODE REVIEW

**Comment by rete** [comment]
Very nice to see some documentation coming! Tell me when you are done

**Comment by rete** [comment]
Hi Julian! Any progress on this PR?
Cheers

**Comment by rete** [comment]
@JBenda Ping

**Comment by JBenda** [comment]
Sorry, for this late action, I updated the Scheme to svg, hope everything looks nice

**Review by rete — APPROVED** [review]

**Pull request merged**
